ci:
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "🗄 chore: pre-commit autoupdate"

default_language_version:
  ruby: 3.1.2

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/rubocop/rubocop
    rev: v1.48.0
    hooks:
      - id: rubocop
        additional_dependencies:
          - rubocop-rails
